//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_programowanie_obiektowe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrzychodniaProjectDBEntities : DbContext
    {
        public PrzychodniaProjectDBEntities()
            : base("name=PrzychodniaProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Choroby> Choroby { get; set; }
        public virtual DbSet<Lekarze> Lekarze { get; set; }
        public virtual DbSet<Pacjenci> Pacjenci { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Wizyty> Wizyty { get; set; }
    }
}
