//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_programowanie_obiektowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wizyty()
        {
            this.Choroby = new HashSet<Choroby>();
        }
    
        public long nr_wizyty { get; set; }
        public System.DateTime data_wizyty { get; set; }
        public string pesel_pacjenta { get; set; }
        public int nr_lekarza { get; set; }
    
        public virtual Lekarze Lekarze { get; set; }
        public virtual Pacjenci Pacjenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Choroby> Choroby { get; set; }
    }
}
